"""Active AI Danger Detector backend API."""

from .evidence_schema import (
    EvidenceQualityTier,
    EvidenceType,
    EvidenceUnit,
    OutcomeLabel,
    OversightLabel,
    UserExpertise,
)
from .evidence_corpus import DataSnapshot, EvidenceCorpus, EvidenceSplit
from .evidence_io import (
    EvidenceLoadError,
    load_corpus,
    load_evidence_units,
    load_source_registry,
)
from .bayesian_calibration import (
    BetaObservation,
    BetaPosterior,
    BetaPrior,
    update_beta_binomial,
)
from .calibration_observations import (
    CalibrationObservationConfig,
    CalibrationObservationSet,
    CalibrationParameter,
    ExcludedEvidence,
    build_calibration_observations,
)
from .evaluation_runner import EvaluationReport, EvaluationRow, evaluate_corpus
from .model_comparison import (
    ModelComparisonReport,
    ModelComparisonRow,
    ScorerDefinition,
    ScorerOutputType,
    baseline_rubric_scorer,
    compare_models,
)
from .reference_scorers import (
    always_assisted_scorer,
    always_casual_scorer,
    always_expert_led_scorer,
    always_expert_review_scorer,
    always_trained_review_scorer,
    reference_policy_scorers,
)

from .numerical_framework import (
    DistributionSpec,
    MarkovState,
    ScenarioSpec,
    SampledScenario,
    SimulationConfig,
    SimulationResult,
    WorkflowResult,
    build_transition_matrix,
    calculate_oversight_score,
    evaluate_markov_workflow,
    run_monte_carlo,
    summarize_simulation,
    validate_transition_matrix,
)
from .performance_metrics import (
    brier_score,
    expected_calibration_error,
    false_escalation_rate,
    false_reassurance_rate,
    interval_coverage,
    log_loss,
)
from .rubric_scorer import (
    DEFAULT_RUBRIC_CONFIG,
    RubricScore,
    RubricScoringConfig,
    score_evidence_unit,
    score_feature_row,
)
from .source_registry import (
    EvidenceSource,
    SourceAuditEvent,
    SourceRegistry,
    SourceStatus,
    SourceType,
)

__all__ = [
    "BetaObservation",
    "BetaPosterior",
    "BetaPrior",
    "CalibrationObservationConfig",
    "CalibrationObservationSet",
    "CalibrationParameter",
    "DistributionSpec",
    "DataSnapshot",
    "DEFAULT_RUBRIC_CONFIG",
    "EvidenceSource",
    "EvidenceCorpus",
    "EvidenceLoadError",
    "EvidenceSplit",
    "EvaluationReport",
    "EvaluationRow",
    "EvidenceQualityTier",
    "EvidenceType",
    "EvidenceUnit",
    "ExcludedEvidence",
    "MarkovState",
    "ModelComparisonReport",
    "ModelComparisonRow",
    "OutcomeLabel",
    "RubricScore",
    "RubricScoringConfig",
    "OversightLabel",
    "ScenarioSpec",
    "ScorerDefinition",
    "ScorerOutputType",
    "SampledScenario",
    "SimulationConfig",
    "SimulationResult",
    "SourceAuditEvent",
    "SourceRegistry",
    "SourceStatus",
    "SourceType",
    "UserExpertise",
    "WorkflowResult",
    "always_assisted_scorer",
    "always_casual_scorer",
    "always_expert_led_scorer",
    "always_expert_review_scorer",
    "always_trained_review_scorer",
    "baseline_rubric_scorer",
    "build_transition_matrix",
    "build_calibration_observations",
    "brier_score",
    "calculate_oversight_score",
    "compare_models",
    "evaluate_markov_workflow",
    "evaluate_corpus",
    "expected_calibration_error",
    "false_escalation_rate",
    "false_reassurance_rate",
    "interval_coverage",
    "log_loss",
    "load_corpus",
    "load_evidence_units",
    "load_source_registry",
    "reference_policy_scorers",
    "run_monte_carlo",
    "score_evidence_unit",
    "score_feature_row",
    "summarize_simulation",
    "update_beta_binomial",
    "validate_transition_matrix",
]
